/// Un ordine consegnato. Base dei tempi e dei venditori.
table Ordini

	/// chiave dell'ordine
	column order_id
		dataType: string
		sourceColumn: order_id

	/// chiave cliente-ordine, NON la persona (vedi Clienti)
	column customer_id
		dataType: string
		sourceColumn: customer_id

	column order_status
		dataType: string
		sourceColumn: order_status

	column order_purchase_timestamp
		dataType: dateTime
		sourceColumn: order_purchase_timestamp

	column order_approved_at
		dataType: dateTime
		sourceColumn: order_approved_at

	column order_delivered_carrier_date
		dataType: dateTime
		sourceColumn: order_delivered_carrier_date

	column order_delivered_customer_date
		dataType: dateTime
		sourceColumn: order_delivered_customer_date

	/// data PROMESSA al cliente, non una previsione
	column order_estimated_delivery_date
		dataType: dateTime
		sourceColumn: order_estimated_delivery_date

	/// giorni fra la data promessa e la data di consegna; positivo = in ritardo
	column giorni_ritardo
		dataType: int64
		sourceColumn: giorni_ritardo

	column in_ritardo
		dataType: boolean
		sourceColumn: in_ritardo

	/// in orario / in ritardo, in parole invece che Vero-Falso
	column esito_consegna
		dataType: string
		sourceColumn: esito_consegna

	/// serve a mostrare il dirupo: il legame non e' una pendenza
	column fascia_ritardo
		dataType: string
		sourceColumn: fascia_ritardo
		sortByColumn: fascia_ordine

	/// ordina le fasce; l'ordine alfabetico sarebbe sbagliato
	column fascia_ordine
		dataType: int64
		isHidden
		sourceColumn: fascia_ordine

	/// approvazione -> affidamento al corriere
	column giorni_fase_venditore
		dataType: double
		sourceColumn: giorni_fase_venditore

	/// affidamento al corriere -> consegna
	column giorni_fase_logistica
		dataType: double
		sourceColumn: giorni_fase_logistica

	/// falso su 1.388 ordini con timestamp incoerenti: escono dalle misure di durata
	column cronologia_ok
		dataType: boolean
		sourceColumn: cronologia_ok

	column data_acquisto
		dataType: dateTime
		sourceColumn: data_acquisto

	column data_consegna
		dataType: dateTime
		sourceColumn: data_consegna

	/// media dei punteggi quando l'ordine ha piu' di una recensione
	column voto
		dataType: double
		sourceColumn: voto

	column recensioni_sull_ordine
		dataType: int64
		sourceColumn: recensioni_sull_ordine

	/// voto <= 2
	column voto_negativo
		dataType: boolean
		sourceColumn: voto_negativo

	/// distingue le due basi: 96.470 consegnati, 95.824 recensiti
	column recensito
		dataType: boolean
		sourceColumn: recensito

	/// il cliente ha risposto prima che il pacco arrivasse: giudica l'attesa, non la consegna
	column recensione_prima_del_pacco
		dataType: boolean
		sourceColumn: recensione_prima_del_pacco

	/// prima / dopo aver ricevuto il pacco, in parole
	column momento_recensione
		dataType: string
		sourceColumn: momento_recensione

	partition Ordini = m
		mode: import
		source =
				// Query: Ordini   -- tabella dei fatti, grana: un ordine consegnato
				// I passaggi hanno i nomi decisi in DATI-SPORCHI.md.
				//
				// Righe attese: 96.470  (numero 3 di RICONCILIAZIONE.md)
				// di cui recensito = true: 95.824  (numero 4)
				let
				    Origine = OrdiniGrezzi,
				
				    // §1 - solo i consegnati. Gli altri 2.963 non hanno una data di consegna
				    // perche' non sono mai arrivati. Quanti sono lo dice ControlloStatiOrdine.
				    #"Tieni solo gli ordini consegnati" = Table.SelectRows(
				        Origine, each [order_status] = "delivered"
				    ),
				
				    // §2 - otto ordini sono marcati consegnati ma non hanno la data.
				    #"Scarta i consegnati senza data di consegna" = Table.SelectRows(
				        #"Tieni solo gli ordini consegnati",
				        each [order_delivered_customer_date] <> null
				    ),
				
				    // Il ritardo e' rispetto alla data PROMESSA, non a un tempo ragionevole (§4).
				    // Si confrontano due DATE, non due istanti: la promessa e' un giorno e nel file
				    // sta alla mezzanotte, la consegna ha l'ora. Sottraendo gli istanti un pacco
				    // arrivato alle 14 del giorno promesso risultava in ritardo di 0,6 giorni:
				    // erano 1.292 ordini, e la quota in ritardo saliva dal 6,8% all'8,1% (§4b).
				    #"Giorni di ritardo" = Table.AddColumn(
				        #"Scarta i consegnati senza data di consegna",
				        "giorni_ritardo",
				        each Duration.Days(
				            DateTime.Date([order_delivered_customer_date])
				                - DateTime.Date([order_estimated_delivery_date])
				        ),
				        Int64.Type
				    ),
				    #"In ritardo si o no" = Table.AddColumn(
				        #"Giorni di ritardo", "in_ritardo", each [giorni_ritardo] > 0, type logical
				    ),
				    // la stessa cosa in parole: sui grafici "Vero/Falso" non dice niente a nessuno
				    #"Esito della consegna" = Table.AddColumn(
				        #"In ritardo si o no",
				        "esito_consegna",
				        each if [giorni_ritardo] > 0 then "Consegnati in ritardo" else "Consegnati in orario",
				        type text
				    ),
				
				    // Le fasce servono a mostrare il DIRUPO (DATI-SPORCHI.md, ipotesi 1): il legame
				    // fra ritardo e recensione non e' una pendenza, e un indicatore riassuntivo
				    // direbbe il falso. Mostrando le fasce si vede dove succede davvero.
				    // I tagli sono gli stessi dell'analisi: -10, -5, 0, 3, 7, 15, 30 giorni. Con i giorni
				    // interi le etichette dicono gli estremi veri: "4-7" e' da 4 a 7 compresi.
				    #"Fascia di ritardo" = Table.AddColumn(
				        #"Esito della consegna",
				        "fascia_ritardo",
				        each if [giorni_ritardo] <= -10 then "10 gg o piu' in anticipo"
				             else if [giorni_ritardo] <= -5 then "5-9 gg in anticipo"
				             else if [giorni_ritardo] <= 0  then "0-4 gg in anticipo"
				             else if [giorni_ritardo] <= 3  then "1-3 gg di ritardo"
				             else if [giorni_ritardo] <= 7  then "4-7 gg di ritardo"
				             else if [giorni_ritardo] <= 15 then "8-15 gg di ritardo"
				             else if [giorni_ritardo] <= 30 then "16-30 gg di ritardo"
				             else "Oltre 30 gg di ritardo",
				        type text
				    ),
				    // l'ordine alfabetico non e' l'ordine giusto: serve una colonna per ordinarle
				    #"Ordine della fascia" = Table.AddColumn(
				        #"Fascia di ritardo",
				        "fascia_ordine",
				        each if [giorni_ritardo] <= -10 then 1
				             else if [giorni_ritardo] <= -5 then 2
				             else if [giorni_ritardo] <= 0  then 3
				             else if [giorni_ritardo] <= 3  then 4
				             else if [giorni_ritardo] <= 7  then 5
				             else if [giorni_ritardo] <= 15 then 6
				             else if [giorni_ritardo] <= 30 then 7
				             else 8,
				        Int64.Type
				    ),
				
				    // Le due fasi della sotto-domanda 5: quella del venditore e quella del corriere.
				    #"Fase venditore" = Table.AddColumn(
				        #"Ordine della fascia",
				        "giorni_fase_venditore",
				        each Duration.TotalDays([order_delivered_carrier_date] - [order_approved_at]),
				        type number
				    ),
				    #"Fase logistica" = Table.AddColumn(
				        #"Fase venditore",
				        "giorni_fase_logistica",
				        each Duration.TotalDays([order_delivered_customer_date] - [order_delivered_carrier_date]),
				        type number
				    ),
				
				    // §3 - 1.359 ordini risultano partiti prima di essere approvati: su quelli
				    // le fasi vengono negative. Si MARCANO, non si cancellano: restano nel
				    // fatturato e nel conteggio, escono solo dalle misure di durata.
				    // Righe con cronologia_ok = true attese: 95.082
				    #"Marca la cronologia incoerente" = Table.AddColumn(
				        #"Fase logistica",
				        "cronologia_ok",
				        each [giorni_fase_venditore] <> null
				            and [giorni_fase_logistica] <> null
				            and [giorni_fase_venditore] >= 0
				            and [giorni_fase_logistica] >= 0,
				        type logical
				    ),
				
				    // Due colonne data (senza ora) per agganciare il Calendario.
				    // shipping_limit_date NON entra: e' una scadenza contrattuale, e arriva al 2020 (§12).
				    #"Data di acquisto" = Table.AddColumn(
				        #"Marca la cronologia incoerente",
				        "data_acquisto",
				        each DateTime.Date([order_purchase_timestamp]),
				        type date
				    ),
				    #"Data di consegna" = Table.AddColumn(
				        #"Data di acquisto",
				        "data_consegna",
				        each DateTime.Date([order_delivered_customer_date]),
				        type date
				    ),
				
				    // Il voto sta qui e non in una tabella a parte, perche' RecensioniPerOrdine
				    // ha gia' grana un-ordine (§5): tenerla separata aggiungerebbe una relazione
				    // uno-a-uno senza guadagnarci niente.
				    #"Aggancia il voto della recensione" = Table.NestedJoin(
				        #"Data di consegna", {"order_id"},
				        RecensioniPerOrdine, {"order_id"},
				        "rec", JoinKind.LeftOuter
				    ),
				    #"Espandi il voto" = Table.ExpandTableColumn(
				        #"Aggancia il voto della recensione",
				        "rec",
				        {"voto", "recensioni_sull_ordine", "voto_negativo", "prima_risposta"},
				        {"voto", "recensioni_sull_ordine", "voto_negativo", "prima_risposta"}
				    ),
				
				    // LE DUE BASI, dichiarate come colonna invece che ricordate a memoria:
				    // tempi e venditori -> tutti i 96.470;  voti -> i 95.824 con recensito = true.
				    #"Segna se recensito" = Table.AddColumn(
				        #"Espandi il voto", "recensito", each [voto] <> null, type logical
				    ),
				
				    // §16 - Olist manda il questionario il giorno dopo la consegna, ma se il pacco
				    // e' in ritardo non lo aspetta: lo manda due giorni dopo la data promessa (4.460
				    // ritardi su 6.409 recensioni). Chi aspetta riceve la domanda mentre il pacco non
				    // c'e', e risponde lo stesso: sui ritardi succede 7 volte su 10. Quelle
				    // recensioni giudicano l'attesa, non la consegna, e vanno contate a parte.
				    // Si confronta la PRIMA risposta con l'istante di consegna.
				    #"Recensione prima del pacco" = Table.AddColumn(
				        #"Segna se recensito",
				        "recensione_prima_del_pacco",
				        each [recensito] and [prima_risposta] <> null
				            and [prima_risposta] < [order_delivered_customer_date],
				        type logical
				    ),
				    #"Momento della recensione" = Table.AddColumn(
				        #"Recensione prima del pacco",
				        "momento_recensione",
				        each if not [recensito] then "Non recensito"
				             else if [recensione_prima_del_pacco] then "Prima di ricevere il pacco"
				             else "Dopo aver ricevuto il pacco",
				        type text
				    ),
				    #"Togli l'istante della risposta" = Table.RemoveColumns(
				        #"Momento della recensione", {"prima_risposta"}
				    )
				in
				    #"Togli l'istante della risposta"

